language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "b70b2417adf81314f5ab56c270b6b6c891da7a7b"
    token:
      secure: "$SONAR_TOKEN"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
